/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Adapted for Agent Alex / Kupuri Media — Synthia 3.0™
*/
"use client";
import React, { useRef, useMemo } from "react";
import { useGLTF } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import * as THREE from "three";
import { useAvatarContext } from "@/context/AvatarContext";

export default function WizardModel(props: Record<string, unknown>) {
  const { nodes, materials } = useGLTF("/models/wizard-transformed.glb");
  const modelRef = useRef<THREE.Group>(null!);
  const { isReacting } = useAvatarContext();

  useFrame((state) => {
    if (!modelRef.current) return;
    // Vertical bobbing
    modelRef.current.position.y =
      -1.5 + Math.sin(state.clock.elapsedTime) * 0.15;

    // Mexican "no" finger-wag: rapid Y-axis oscillation when reacting
    if (isReacting) {
      modelRef.current.rotation.y =
        Math.sin(state.clock.elapsedTime * 11) * 0.28;
    } else {
      // Smooth return to base rotation
      modelRef.current.rotation.y +=
        (0 - modelRef.current.rotation.y) * 0.12;
    }
  });

  return (
    <group
      {...props}
      ref={modelRef}
      dispose={null}
      position={[0, -1.5, 0]}
      scale={[0.06, 0.06, 0.06]}
      rotation={[0.25, 0, 0]}
    >
      <mesh castShadow receiveShadow geometry={(nodes.Evil_Hathattty_mesh_Evil_HatBLN_Hat_0 as THREE.Mesh).geometry}       material={getMat("Evil_HatBLN_Hat")}     {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.WandpCylinder1_Wandq_0 as THREE.Mesh).geometry}                      material={getMat("PaletteMaterial001")}   {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.R_shoe_tongue_mesh_BLN_Shoe_tongue_0 as THREE.Mesh).geometry}        material={getMat("BLN_Shoe_tongue")}      {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.Chest_piece_mesh_BLN_chest_piece_0 as THREE.Mesh).geometry}          material={getMat("BLN_chest_piece")}      {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.Right_Eyeball_Mesh_Lam_eyeball_0 as THREE.Mesh).geometry}            material={getMat("material_0")}           {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.pants_mesh_BLN_Pants_0 as THREE.Mesh).geometry}                     material={getMat("BLN_Pants")}            {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.lower_coat_mesh_FK_BLN_Lower_coat_0 as THREE.Mesh).geometry}        material={getMat("BLN_Lower_coat")}       {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.R_shoe_mesh_BLN_shoes_0 as THREE.Mesh).geometry}                    material={getMat("BLN_shoes")}            {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.Upper_coat_mesh_BLN_upper_coat_0 as THREE.Mesh).geometry}           material={getMat("BLN_upper_coat")}       {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.upper_body_mesh_BLN_shirt_0 as THREE.Mesh).geometry}                material={getMat("BLN_shirt")}            {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.upper_body_mesh_BLN_Shirt_collar_0 as THREE.Mesh).geometry}         material={getMat("BLN_Shirt_collar")}     {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.Coat_collar_mesh_BLN_collar_piece_0 as THREE.Mesh).geometry}        material={getMat("BLN_collar_piece")}     {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.BookpolySurface5_Bookblinn1_0 as THREE.Mesh).geometry}              material={getMat("Bookblinn1")}           {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.BookBook_corner_mesh4_Booklam_book_corners_0 as THREE.Mesh).geometry} material={getMat("Booklam_book_corners")} {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.BookpolySurface20_BookBLN_Metal_parts_0 as THREE.Mesh).geometry}    material={getMat("BookBLN_Metal_parts")}  {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.BookFront_glow_mesh_Booklambert8_0 as THREE.Mesh).geometry}         material={getMat("PaletteMaterial002")}   {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.BookpolySurface2_BookBLN_Book_covers_0 as THREE.Mesh).geometry}     material={getMat("BookBLN_Book_covers")}  {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.BookpCube10_Booklam_front_bits_0 as THREE.Mesh).geometry}           material={getMat("material_2")}           {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.BookpolySurface28_Booklam_back_bits_0 as THREE.Mesh).geometry}      material={getMat("Booklam_back_bits")}    {...sharedProps} />
      <mesh castShadow receiveShadow geometry={(nodes.Evil_HatpPlane1_Evil_HatsolidShader_0 as THREE.Mesh).geometry}      material={getMat("PaletteMaterial003")}   {...sharedProps} />
    </group>
  );
}

// FIX: path must match the actual model URL used in useGLTF above
useGLTF.preload("/models/wizard-transformed.glb");
